### ISSUE TITLE
Linking.openUrl not always working

### ISSUE THREAD

**Issue by danielmocan** [jsheroes/javascript-knowledge#2]
I'm trying to open a link from the React Native app.
For this, I'm using `Linking` from `react-native package`.

The problem is that only sometimes opens the link. In other cases it does nothing.

I also change the `<Text>` component with a `<TouchableOpacity>` but its still the same issue.
The problem is not from the `if` check, because the url its always valid ( and to falsy )

Anyone else had the same issue,  any ideas to fix this issue?

### Code Sample
```javascript
  handlerOpenLink = url => {
    if (url) {
      Linking.openURL(url);
    } else {
      Alert.alert( "some message" );
    }
  };

return 
   <View>
     <Text
        onPress={ () => this.handlerOpenLink(url)}
      >
        Open Link
      </Text>
   </View>
```

**Comment by emimuresan** [comment]
Hi @danielmocan ! I'd recommend adding a catch:

```js 
   Linking.openURL(url).catch((err) => {
      console.warn(`An error occurred for ${url}`, err);
    });
```
to investigate further.

Note: if you have a mailto link that does not work in the simulator but works on a real device.

**Comment by danielmocan** [comment]
Wrong repo :), I wanted to ask on the JSHeroes React Native Community Repo https://github.com/jsheroes/react-native-community
